# Generated by Django 2.2.5 on 2021-12-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211218_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='job_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.JobCategory'),
        ),
    ]
