# Generated by Django 4.0 on 2021-12-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211218_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribed_companies',
        ),
    ]
