# Generated by Django 2.2.11 on 2021-11-19 14:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211119_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='prof_cv',
            field=models.FileField(null=True, upload_to=accounts.models.profile_cv_folder),
        ),
    ]
