# Generated by Django 2.2.11 on 2021-11-19 15:08

import addbanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=addbanner.models.add_image_folder)),
            ],
        ),
    ]
